"use client";

import { useEffect,useMemo,useRef,useState } from "react";
import Link from "next/link";
import { createClient } from "@/lib/supabase/client";
import styles from "@/app/account/account.module.css";

type Message={id:string;conversation_id:string;sender_id:string;body:string;created_at:string};
export function ChatClient({conversationId,currentUserId,title,requestId}:{conversationId:string;currentUserId:string;title:string;requestId:string}){const supabase=useMemo(()=>createClient(),[]);const [messages,setMessages]=useState<Message[]>([]);const [body,setBody]=useState("");const [status,setStatus]=useState("");const endRef=useRef<HTMLDivElement|null>(null);
useEffect(()=>{let active=true;void supabase.from("messages").select("id,conversation_id,sender_id,body,created_at").eq("conversation_id",conversationId).order("created_at").then(({data})=>{if(active)setMessages((data||[]) as Message[])});const channel=supabase.channel(`conversation:${conversationId}`).on("postgres_changes",{event:"INSERT",schema:"public",table:"messages",filter:`conversation_id=eq.${conversationId}`},payload=>{const next=payload.new as Message;setMessages(old=>old.some(m=>m.id===next.id)?old:[...old,next])}).subscribe();return()=>{active=false;void supabase.removeChannel(channel)}},[conversationId,supabase]);useEffect(()=>{endRef.current?.scrollIntoView({behavior:"smooth"})},[messages]);
async function send(e:React.FormEvent){e.preventDefault();const text=body.trim();if(!text)return;setBody("");const {error}=await supabase.from("messages").insert({conversation_id:conversationId,sender_id:currentUserId,body:text});if(error){setBody(text);setStatus(error.message)}else setStatus("")}
return <section className={styles.page}><div className={styles.wrap} style={{maxWidth:900}}><div className={styles.head}><div><span className="eyebrow">CAKELIO CHAT</span><h1>{title}</h1><p>Request {requestId.slice(0,8)} · Keep design, quote and order questions in this conversation.</p></div><Link className={styles.link} href="/account">Account →</Link></div><div className={styles.card} style={{padding:0,overflow:"hidden"}}><div style={{height:"min(58vh,560px)",overflowY:"auto",padding:20,display:"flex",flexDirection:"column",gap:10}}>{messages.length===0&&<div className={styles.empty}>No messages yet. Say hello and clarify the cake details.</div>}{messages.map(m=><div key={m.id} style={{alignSelf:m.sender_id===currentUserId?"flex-end":"flex-start",maxWidth:"78%",background:m.sender_id===currentUserId?"#352620":"#FFF8F2",color:m.sender_id===currentUserId?"#FFF8F2":"#352620",border:"1px solid #E6D9CF",borderRadius:16,padding:"10px 13px"}}><div style={{whiteSpace:"pre-wrap",lineHeight:1.5}}>{m.body}</div><small style={{display:"block",opacity:.65,marginTop:5}}>{new Date(m.created_at).toLocaleTimeString("de-DE",{hour:"2-digit",minute:"2-digit"})}</small></div>)}<div ref={endRef}/></div><form onSubmit={send} style={{borderTop:"1px solid #E6D9CF",padding:14,display:"flex",gap:8}}><input aria-label="Message" value={body} onChange={e=>setBody(e.target.value)} maxLength={5000} placeholder="Write a message…" style={{flex:1,border:"1px solid #E6D9CF",borderRadius:999,padding:"12px 15px",background:"#FFF8F2",color:"#352620"}}/><button className={styles.primary}>Send</button></form>{status&&<div className={styles.notice}>{status}</div>}</div></div></section>}
