"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";
import styles from "@/app/account/account.module.css";

type Baker = { user_id:string; business_name:string; minimum_lead_days:number; starting_price:number|null; currency:string; city:string|null };

export function OrderRequestForm({ baker }: { baker:Baker }) {
  const router=useRouter(); const supabase=useMemo(()=>createClient(),[]);
  const [design,setDesign]=useState<Record<string,unknown>>({}); const [status,setStatus]=useState("");
  useEffect(()=>{try{const raw=localStorage.getItem("cakelio-studio-draft");if(raw)setDesign(JSON.parse(raw));}catch{}},[]);
  const minDate=useMemo(()=>{const d=new Date();d.setDate(d.getDate()+baker.minimum_lead_days);return d.toISOString().slice(0,10)},[baker.minimum_lead_days]);
  async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setStatus("Creating your request…");const form=new FormData(e.currentTarget);const {data,error}=await supabase.rpc("submit_order_request",{p_provider_id:baker.user_id,p_design_name:String(form.get("design_name")||"Custom cake"),p_design_config:design,p_event_date:String(form.get("event_date")),p_fulfillment_type:String(form.get("fulfillment_type")||"pickup"),p_delivery_city:String(form.get("delivery_city")||"")||null,p_delivery_postal_code:String(form.get("delivery_postal_code")||"")||null,p_budget_min:null,p_budget_max:form.get("budget_max")?Number(form.get("budget_max")):null,p_notes:String(form.get("notes")||"")||null});if(error)return setStatus(error.message);const result=data as {conversation_id?:string};if(result?.conversation_id)router.push(`/messages/${result.conversation_id}`);else setStatus("Request created.");}
  return <section className={styles.page}><div className={styles.wrap} style={{maxWidth:860}}><span className="eyebrow">PLACE A CAKE ORDER</span><div className={styles.head}><div><h1>Order from {baker.business_name}.</h1><p>Your request starts a private conversation. The baker reviews the design and sends a final quote before you pay.</p></div></div><form className={styles.card} onSubmit={submit}><div className={styles.formGrid}><label className={styles.field}><span>Design name</span><input name="design_name" defaultValue="My custom cake"/></label><label className={styles.field}><span>Event date</span><input type="date" name="event_date" min={minDate} required/></label><label className={styles.field}><span>Pickup or delivery</span><select name="fulfillment_type"><option value="pickup">Pickup</option><option value="delivery">Delivery</option></select></label><label className={styles.field}><span>Maximum budget (€)</span><input type="number" min="0" step="0.01" name="budget_max" placeholder={baker.starting_price?String(baker.starting_price):""}/></label><label className={styles.field}><span>Delivery city (if needed)</span><input name="delivery_city" defaultValue={baker.city||""}/></label><label className={styles.field}><span>Postal code</span><input name="delivery_postal_code"/></label><label className={`${styles.field} ${styles.full}`}><span>Message to the baker</span><textarea name="notes" placeholder="Occasion, serving count, allergies, inspiration, delivery details…"/></label></div>{Object.keys(design).length>0&&<div className={styles.notice}>✓ Your latest Cakelio Studio design is attached to this request.</div>}<div className={styles.actions}><button className={styles.primary}>Send order request</button>{status&&<span className={styles.status}>{status}</span>}</div></form></div></section>;
}
