import Link from "next/link";
import { Footer } from "@/components/Footer";
import { Nav } from "@/components/Nav";

const benefits = [
  ["Structured requests", "Customers choose the size, flavour, filling, finish, decoration, event date and delivery needs before they contact you."],
  ["Your own ordering link", "Use your Cakelio page in Instagram, WhatsApp, Google Business or your own website — even before the public marketplace grows."],
  ["Capability controls", "Only show customers combinations you actually make: tiers, finishes, dietary options, lead times and service radius."],
  ["One order timeline", "Keep messages, quote revisions, inspiration photos, deposits and status attached to the same request."],
];

export default function ForBakersPage(){return <main><Nav /><section className="proHero shell"><div><span className="eyebrow">CAKELIO PRO</span><h1>Spend less time clarifying.<br/><em>More time creating.</em></h1><p>Give every customer a guided way to explain the cake they want — then decide which requests you accept.</p><div className="heroActions"><button className="button buttonPrimary buttonLarge">Join the baker waitlist</button><Link className="button buttonSoft buttonLarge" href="/studio">Try the Cake Studio</Link></div></div><div className="providerPhone"><div className="providerPhoneHead"><span>Good morning, Mila</span><b>●</b></div><div className="providerMetric"><small>Requests to review</small><strong>6</strong></div><div className="providerRequest"><div><b>Emma’s 30th birthday</b><span>20 cm · Chocolate · Floral</span></div><em>€80–€110</em></div><div className="providerRequest"><div><b>Wedding tasting</b><span>3 flavours · 8 Nov</span></div><em>New</em></div><div className="providerRequest"><div><b>Leo’s dinosaur cake</b><span>Fondant · 16 servings</span></div><em>Quoted</em></div></div></section><section className="section shell"><div className="sectionHeading"><div><span className="eyebrow">WHY PROVIDERS USE IT</span><h2>A useful tool before it becomes a marketplace.</h2></div><p>The baker dashboard is intentionally part of the core product, not an afterthought.</p></div><div className="benefitGrid">{benefits.map(([title,text],i)=><article key={title}><span>0{i+1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section><section className="waitlistBand"><div className="shell"><span className="eyebrow eyebrowLight">EARLY PROVIDER PROGRAM</span><h2>Help shape Cakelio Pro.</h2><p>We’ll begin with independent custom cake makers and boutique cake studios, learn their real workflow and build around it.</p><button className="button buttonCream buttonLarge">I’m interested as a baker</button></div></section><Footer /></main>}
